services:
  diet-tracker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: diet-tracker
    ports:
      - "7778:80"
    volumes:
      - ./docker-data:/data
    restart: unless-stopped
